import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'



export default function Home() {
  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='container'>
          <h1>Quiz App</h1>
          <Link href='/quiz'>
              <button>Start Quiz</button>
          </Link>
        </div>
      </main>
    </>
  )
}
